#Dataset Cleanup

Input format :-  

FormID: str	str	str int str

Eg
FormID: 00092D86	MQ02	MQ02JauffreD2	0	His meaning is unclear to me as well. The Emperor seemed to perceive some threat from the demonic world of Oblivion.

#Find txt file encoding type

In [ ]:
import chardet
import glob

# for every text file, print the file name & a gues of its file encoding
print("File".ljust(45), "Encoding")
for filename in glob.glob('/content/*.txt'):
    with open(filename, 'rb') as rawdata:
        result = chardet.detect(rawdata.read())
    print(filename.ljust(45), result['encoding'])

File                                          Encoding
/content/input.txt                            utf-8
/content/shakespeare.txt                      ascii
/content/OblivionGOTY_Dialog.txt              Windows-1252
/content/SkyrimGOTY_Dialogue.txt              ascii


In [ ]:
#convert encoding type
with open('/content/OblivionGOTY_Dialog.txt', 'r', encoding='cp1252') as inp,\
        open('input.txt', 'w', encoding='utf-8') as outp:
    for line in inp:
        outp.write(line)

In [ ]:
with open('input.txt','r', encoding='utf-8' ) as f:
  text = f.read()

In [ ]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  3348672


In [ ]:
print(text[:1000])

FormID: 00092D86	MQ02	MQ02JauffreD2	0	His meaning is unclear to me as well. The Emperor seemed to perceive some threat from the demonic world of Oblivion. 	
FormID: 00092D86	MQ02	MQ02JauffreD2	1	The Prince of Destruction, Mehrunes Dagon, is one of the lords of Oblivion.	grimly
FormID: 00092D86	MQ02	MQ02JauffreD2	2	But the mortal world is protected from the daedra of Oblivion by magical barriers.	puzzled by the apparent contradiction
FormID: 0002B09E	MS22	MS22CleansingFane	0	I don't own it. One of the rare book dealers in the Market District may have a copy. Read it. Educate yourself.	
FormID: 000860C2	MS91	MazogaWoman	0	I'm a knight. So say, 'Sir'. Say, 'Yes, Sir Mazoga'.	
FormID: 000ADD45	MQ00	MQ16OcatoC	0	Then Martin is gone...	trying to accept this
FormID: 000980FC	MS31	MS31Selene03Negative	0	Wrong, fool. I've grown tired of this guessing game. I've much to do and you're in the way. I aim to rectify that!	
FormID: 000980FB	MS31	MS31Selene03aPositive	0	What? Can no one in this gang k

#Clean txt file

FormID: 00092D86	MQ02	MQ02JauffreD2	0	His meaning is unclear to me as well. The Emperor seemed to perceive some threat from the demonic world of Oblivion.

To

His meaning is unclear to me as well. The Emperor seemed to perceive some threat from the demonic world of Oblivion.


In [ ]:
import pandas as pd
df = pd.read_csv("input.txt", sep="\s+", on_bad_lines='skip')
df = df.drop('FormID:', axis=1)
df = df.drop('00092D86', axis=1)
df = df.drop('MQ02', axis=1)
df = df.drop('MQ02JauffreD2', axis=1)
df = df.drop('0', axis=1)
print(df)
df.to_csv('input1.txt', sep='\t', index=False)


             His  meaning        is       unclear        to         me  \
0            The   Prince        of  Destruction,  Mehrunes     Dagon,   
1            But      the    mortal         world        is  protected   
2            I'm        a   knight.            So      say,     'Sir'.   
3           Then   Martin        is       gone...    trying         to   
4          What?      Can        no           one        in       this   
...          ...      ...       ...           ...       ...        ...   
17183       Once     they     break    themselves        on        our   
17184         Of      the  original      divines,  Zenithar         is   
17185  Craftsmen  devoted        to      Zenithar       are       able   
17186         Of      the  original      divines,  Zenithar         is   
17187  Craftsmen  devoted        to      Zenithar       are       able   

              as    well.     The   Emperor  ... to.1   perceive       some  \
0             is      one      o

In [ ]:
with open('input1.txt','r', encoding='utf-8' ) as f:
  text = f.read()

In [ ]:
print(text[:1000])

His	meaning	is	unclear	to	me	as	well.	The	Emperor	seemed	to.1	perceive	some	threat	from	the	demonic	world	of	Oblivion.
The	Prince	of	Destruction,	Mehrunes	Dagon,	is	one	of	the	lords	of	Oblivion.	grimly							
But	the	mortal	world	is	protected	from	the	daedra	of	Oblivion	by	magical	barriers.	puzzled	by	the	apparent	contradiction		
I'm	a	knight.	So	say,	'Sir'.	Say,	'Yes,	Sir	Mazoga'.											
Then	Martin	is	gone...	trying	to	accept	this													
What?	Can	no	one	in	this	gang	keep	things	secret?											
I	suppose	you	think	you	know	why	we've	taken	over	the	Bloated	Float	as	well!						
You	don't	have	the	gold.	I	hope	you	didn't	think	I	was	just	going	to	give	it	to	you?	indignant	
What	a	pity.																		
Excellent!	Go	out	to	the	corral.	Antione	will	have	your	new	Bay	saddled	and	ready	for	you.				
You	should	only	have	goodbye	as	your	option.													
It's	a	pleasure	to	have	you	become	a	citizen	of	Chorrol.	I'll	take	care	of	the	deed.				
Here	is	your	key.	The	house	is	on

In [ ]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)

	
!&'()*,-./0123456789:;<=>?ABCDEFGHIJKLMNOPQRSTUVWXYZ[]_abcdefghijklmnopqrstuvwxyzë…
85


In [ ]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("sgfdjhgkhg"))
print(decode(encode("sgfdjhgkhg")))

[75, 63, 62, 60, 66, 64, 63, 67, 64, 63]
sgfdjhgkhg


In [ ]:
#store data to torch tensor
import torch
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # the 1000 characters we looked at earier will to the GPT look like this

torch.Size([1295715]) torch.int64
tensor([35, 65, 75,  0, 69, 61, 57, 70, 65, 70, 63,  0, 65, 75,  0, 77, 70, 59,
        68, 61, 57, 74,  0, 76, 71,  0, 69, 61,  0, 57, 75,  0, 79, 61, 68, 68,
        10,  0, 47, 64, 61,  0, 32, 69, 72, 61, 74, 71, 74,  0, 75, 61, 61, 69,
        61, 60,  0, 76, 71, 10, 13,  0, 72, 61, 74, 59, 61, 65, 78, 61,  0, 75,
        71, 69, 61,  0, 76, 64, 74, 61, 57, 76,  0, 62, 74, 71, 69,  0, 76, 64,
        61,  0, 60, 61, 69, 71, 70, 65, 59,  0, 79, 71, 74, 68, 60,  0, 71, 62,
         0, 42, 58, 68, 65, 78, 65, 71, 70, 10,  1, 47, 64, 61,  0, 43, 74, 65,
        70, 59, 61,  0, 71, 62,  0, 31, 61, 75, 76, 74, 77, 59, 76, 65, 71, 70,
         8,  0, 40, 61, 64, 74, 77, 70, 61, 75,  0, 31, 57, 63, 71, 70,  8,  0,
        65, 75,  0, 71, 70, 61,  0, 71, 62,  0, 76, 64, 61,  0, 68, 71, 74, 60,
        75,  0, 71, 62,  0, 42, 58, 68, 65, 78, 65, 71, 70, 10,  0, 63, 74, 65,
        69, 68, 81,  0,  0,  0,  0,  0,  0,  0,  1, 29, 77, 76,  0, 76, 64, 61,
      

In [ ]:
# Let's now split up the data into train and validation sets
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [ ]:
block_size = 8
train_data[:block_size+1]

tensor([35, 65, 75,  0, 69, 61, 57, 70, 65])

In [ ]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([35]) the target: 65
when input is tensor([35, 65]) the target: 75
when input is tensor([35, 65, 75]) the target: 0
when input is tensor([35, 65, 75,  0]) the target: 69
when input is tensor([35, 65, 75,  0, 69]) the target: 61
when input is tensor([35, 65, 75,  0, 69, 61]) the target: 57
when input is tensor([35, 65, 75,  0, 69, 61, 57]) the target: 70
when input is tensor([35, 65, 75,  0, 69, 61, 57, 70]) the target: 65


In [ ]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[ 0,  0,  0,  0,  0,  0,  0,  1],
        [68, 65, 61, 78, 61,  0, 76, 64],
        [77, 75,  0, 36, 70, 78, 61, 70],
        [71, 77,  0, 79, 71, 70,  4, 76]])
targets:
torch.Size([4, 8])
tensor([[ 0,  0,  0,  0,  0,  0,  1, 36],
        [65, 61, 78, 61,  0, 76, 64, 57],
        [75,  0, 36, 70, 78, 61, 70, 76],
        [77,  0, 79, 71, 70,  4, 76,  0]])
----
when input is [0] the target: 0
when input is [0, 0] the target: 0
when input is [0, 0, 0] the target: 0
when input is [0, 0, 0, 0] the target: 0
when input is [0, 0, 0, 0, 0] the target: 0
when input is [0, 0, 0, 0, 0, 0] the target: 0
when input is [0, 0, 0, 0, 0, 0, 0] the target: 1
when input is [0, 0, 0, 0, 0, 0, 0, 1] the target: 36
when input is [68] the target: 65
when input is [68, 65] the target: 61
when input is [68, 65, 61] the target: 78
when input is [68, 65, 61, 78] the target: 61
when input is [68, 65, 61, 78, 61] the target: 0
when input is [68, 65, 61, 78, 61, 0] the target: 76

In [ ]:
print(xb) # our input to the transformer

tensor([[ 0,  0,  0,  0,  0,  0,  0,  1],
        [68, 65, 61, 78, 61,  0, 76, 64],
        [77, 75,  0, 36, 70, 78, 61, 70],
        [71, 77,  0, 79, 71, 70,  4, 76]])


In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([32, 85])
tensor(4.9580, grad_fn=<NllLossBackward0>)
	DA
jHPYgtds2GB
HO71axBO!-EBpU18'23FIMëa_IpvpwP;6oQ8lnNgvwH_qs'Syc&b-a&<Xka183Cp/tdV;rJ
BeNDHr50TR<;h


In [ ]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [ ]:
batch_size = 32
for steps in range(150): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


4.947105407714844


In [ ]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))

	ëfD*nv['SC=N)&lT;rWjpZJBoM3'[
1	4<	*G8pds4b&Q=BG8>8NN6KTblHJWw87JG7JJ2hzx;K7cc7WRxSWnRxO0'Cl]MZjBp3M4SeD,0HDwI&n9aOsqkQ9Cg<7plx9.'.DgGFI=7&(jP?…CXg9!7GUAQJGBpg;]]FI]a_AkRR;N[iO!/>'5'KjHSL)UNO0&yëj1_Jy1Md-&*).vëL/T.IW!1:A7;>=q.05.]E4y?PhIë>hIHpWsQ_nr)pZ4M…u…N<RbwPnrjf<.Dg9a1q!XA4;NjYa1Jn.4/Cs2x:	D-myLg:ëjWSo_cfmT'tGI:N*	_qoU8p*G)/S=*YEwTUbjhJ(1lHSJJkj_]u,Dnr*7umG,:1VZAQ7kd*:ëSvLi4.BEp)Yl<3ëe4WA?Q)<XQaO!M?MOV(0pI&lOGWS4b*,'-?/d9.7d,T]PYQ9I&lOmP710Jfs.gO,EXoIoR	eY4e;18:N*nQ[Hwh?y&	,DJ.
Ujvy&jjHOP,!


In [ ]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

torch.Size([4, 8, 16])

In [ ]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 5000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0
# ------------

torch.manual_seed(1337)

# wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
# changed to input1.txt
with open('input1.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))

0.212309 M parameters
step 0: train loss 4.8702, val loss 4.7961
step 100: train loss 2.5555, val loss 2.6350
step 200: train loss 2.3573, val loss 2.4322
step 300: train loss 2.2339, val loss 2.3259
step 400: train loss 2.1409, val loss 2.2559
step 500: train loss 2.0971, val loss 2.1961
step 600: train loss 2.0501, val loss 2.1393
step 700: train loss 1.9990, val loss 2.0877
step 800: train loss 1.9690, val loss 2.0535
step 900: train loss 1.9144, val loss 2.0214
step 1000: train loss 1.9053, val loss 1.9759
step 1100: train loss 1.8722, val loss 1.9456
step 1200: train loss 1.8363, val loss 1.9262
step 1300: train loss 1.8234, val loss 1.9119
step 1400: train loss 1.7953, val loss 1.8774
step 1500: train loss 1.7527, val loss 1.8550
step 1600: train loss 1.7436, val loss 1.8461
step 1700: train loss 1.7372, val loss 1.8239
step 1800: train loss 1.7262, val loss 1.8051
step 1900: train loss 1.7222, val loss 1.8076
step 2000: train loss 1.6881, val loss 1.7802
step 2100: train loss 1.

In [ ]:
# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))

	please!													
I	wat	you	can	Lord	I	gland	ub	honaiil	
I	more	quies	let	ready	uptracts	Guild	in-I	hear	shamps	troubled	now	drougns	think	goe.	hen't	keleeps	to	think	derough	whete	may	his	solderhated	engiact	und	a	before	to	veryment	urder!												
The	Let	crove.	Why	alis	nothing	more!	Nother	you	hapirge	in	Cust	safore	this	book	prestectuess	liferich.								
I	doind	housed	to	stome	this	Grovivings	/idy	winger.	Yes?	Here	one	ago	enations.										
Eara	Ok	yone	up....	I	would	a	famages	of	head,	the	sound	hough.	Forksmewayer	Gatess	they	can	abouth	might	is	boods,	in	old	bettable	it	that?												
Intor	the	Take	happatiable.	Nord	he's	trattle.	
Stome	dead	succrvamen	Marien	may	it	calvil	the	Empirion	Glorde	museve	you?	A	rugh?in	ehally	cure	if	the	skowo	her	is	a	dectsmometious	is	over	oble!
Oh!	There's	a	luck.	The	serven	the	Criticeu.				
I	trip?	Beforiee.	
We	deready	hate	this	acconail	watcriong.	
I	have	go	diditurebler.	Baravely.	What's	dealthing	tasky	in	to	gette	of	my	my	pl